[build-system]
requires = ['setuptools', 'wheel']
build-backend = "setuptools.build_meta"

[project]
name='pyorthogonalrouting'
dynamic = ["version"]
description = 'Yet another orthogonal router'
readme = "README.md"
license = 'AGPL-1.0-or-later'
authors = [{name = 'Humberto A. Sanchez II', email = 'Humbert.A.Sanchez.II@gmail.com'}]
maintainers = [{name = 'Humberto A. Sanchez II', email = 'Humbert.A.Sanchez.II@gmail.com'}]
keywords = ['orthogonal', 'routing', 'python', 'pyut']

classifiers = [
  "Programming Language :: Python",
  "Intended Audience :: Developers",
  "Operating System :: MacOS :: MacOS X",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    'codeallybasic>=1.40.1',
]

[project.urls]
Repository = 'https://github.com/hasii2011/py-orthogonal-routing'

[project.optional-dependencies]
test = [
    'mypy==1.20.0',
    'html-testRunner~=1.2.1',
]

deploy = [
    'wheel==0.48.0',
    'setuptools==84.0.0',
    'twine==7.0.0',
    'build==1.6.1',
]

demo = [
    'wxPython==4.3.1',
]

[tool.setuptools.packages.find]
where = ['src']

[tool.setuptools.package-data]
pyutmodel = ['py.typed']

[tool.setuptools.dynamic]
version = {attr = 'pyorthogonalrouting.__version__'}
