
from unittest import TestSuite
from unittest import main as unitTestMain

from os import sep as osSep

from codeallybasic.UnitTestBase import UnitTestBase

from pyorthogonalrouting.Common import Integers
from pyorthogonalrouting.Grid import Grid
from pyorthogonalrouting.Rectangle import Rectangle


class ProjectTestBase(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 11 April 2024
    """
    RESOURCES_TEST_PACKAGE_NAME: str = 'tests.resources'
    RESOURCES_TEST_DIRECTORY:    str = f'tests{osSep}resources'

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def _buildTesGrid(self) -> Grid:

        bigBounds:   Rectangle = Rectangle(left=30, top=30, width=240, height=290)
        bounds:      Rectangle = Rectangle.fromLTRB(bigBounds.left, bigBounds.top, bigBounds.right, bigBounds.bottom)
        verticals:   Integers  = Integers([40, 100, 160, 190, 260])
        horizontals: Integers  = Integers([40, 160, 190, 250, 310])

        grid: Grid = Grid.rulersToGrid(verticals, horizontals, bounds)

        return grid


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=ProjectTestBase))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
