from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from pyorthogonalrouting.Rect import Rect


# import the class you want to test here
# from org.pyut.template import template


class TestRect(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 28 April 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testStr(self):
        """Another test"""

        rect: Rect = Rect(left=200, top=100, width=500, height=1000)

        actualStr:   str = rect.__str__()
        expectedStr: str = '200,100,500,1000'

        self.assertEqual(expectedStr, actualStr, 'I do not understand')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestRect))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
